---
title       : Update the Workflow
subtitle    : 
author      : Data Inquisitor
job         :
github      : {user: datainquisitor, repo: testDeck, branch: "gh-pages"}
framework   : bootplus        # {io2012, html5slides, shower, dzslides, ...}
layout      : post
mode        : selfcontained
highlighter : prettify  # {highlight.js, prettify, highlight}
hitheme     : twitter-bootstrap      # 
lead : >
  Testing bootplus from R
assets:
  js:
    - "http://d3js.org/d3.v3.min.js"
    - "http://dimplejs.org/dist/dimple.v2.0.0.min.js"
    - "http://timelyportfolio.github.io/rCharts_dimple/js/d3-grid.js"
  css:
    - "http://fonts.googleapis.com/css?family=Raleway:300"
    - "http://fonts.googleapis.com/css?family=Oxygen"    
---

# Read-And-Delete

<style>
body{
  font-family: 'Oxygen', sans-serif;
  font-size: 15px;
  line-height: 22px;
}

h1,h2,h3,h4 {
  font-family: 'Raleway', sans-serif;
}

</style>



1. Edit YAML front matter
2. Write using R Markdown
3. Use an empty line followed by three dashes to separate slides!

--- .class #id 

# Some more stuff

insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!
insert a bunch of gibberish here to test scrolling!



---

# Even further stuff




